// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: userclient.proto

package userclientgrpc

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username  string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Passworld string `protobuf:"bytes,2,opt,name=passworld,proto3" json:"passworld,omitempty"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userclient_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_userclient_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_userclient_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetPassworld() string {
	if x != nil {
		return x.Passworld
	}
	return ""
}

type GetBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Username  string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	ShareChan string `protobuf:"bytes,3,opt,name=ShareChan,proto3" json:"ShareChan,omitempty"`
	Sharemode bool   `protobuf:"varint,4,opt,name=sharemode,proto3" json:"sharemode,omitempty"`
	Passworld string `protobuf:"bytes,5,opt,name=passworld,proto3" json:"passworld,omitempty"`
}

func (x *GetBody) Reset() {
	*x = GetBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userclient_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBody) ProtoMessage() {}

func (x *GetBody) ProtoReflect() protoreflect.Message {
	mi := &file_userclient_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBody.ProtoReflect.Descriptor instead.
func (*GetBody) Descriptor() ([]byte, []int) {
	return file_userclient_proto_rawDescGZIP(), []int{1}
}

func (x *GetBody) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetBody) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetBody) GetShareChan() string {
	if x != nil {
		return x.ShareChan
	}
	return ""
}

func (x *GetBody) GetSharemode() bool {
	if x != nil {
		return x.Sharemode
	}
	return false
}

func (x *GetBody) GetPassworld() string {
	if x != nil {
		return x.Passworld
	}
	return ""
}

type PutBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value     []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Datatype  int32  `protobuf:"varint,3,opt,name=datatype,proto3" json:"datatype,omitempty"`
	Username  string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Share     bool   `protobuf:"varint,5,opt,name=share,proto3" json:"share,omitempty"`
	ShareChan string `protobuf:"bytes,6,opt,name=ShareChan,proto3" json:"ShareChan,omitempty"`
	Strict    bool   `protobuf:"varint,7,opt,name=strict,proto3" json:"strict,omitempty"`
	Passworld string `protobuf:"bytes,8,opt,name=passworld,proto3" json:"passworld,omitempty"`
}

func (x *PutBody) Reset() {
	*x = PutBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userclient_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBody) ProtoMessage() {}

func (x *PutBody) ProtoReflect() protoreflect.Message {
	mi := &file_userclient_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBody.ProtoReflect.Descriptor instead.
func (*PutBody) Descriptor() ([]byte, []int) {
	return file_userclient_proto_rawDescGZIP(), []int{2}
}

func (x *PutBody) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutBody) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutBody) GetDatatype() int32 {
	if x != nil {
		return x.Datatype
	}
	return 0
}

func (x *PutBody) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PutBody) GetShare() bool {
	if x != nil {
		return x.Share
	}
	return false
}

func (x *PutBody) GetShareChan() string {
	if x != nil {
		return x.ShareChan
	}
	return ""
}

func (x *PutBody) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

func (x *PutBody) GetPassworld() string {
	if x != nil {
		return x.Passworld
	}
	return ""
}

type VerifyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Info   string `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *VerifyInfo) Reset() {
	*x = VerifyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userclient_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyInfo) ProtoMessage() {}

func (x *VerifyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_userclient_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyInfo.ProtoReflect.Descriptor instead.
func (*VerifyInfo) Descriptor() ([]byte, []int) {
	return file_userclient_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyInfo) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *VerifyInfo) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type ResQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 查找状态
	Data   []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`      // 数据(如果找到的)
}

func (x *ResQuery) Reset() {
	*x = ResQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userclient_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResQuery) ProtoMessage() {}

func (x *ResQuery) ProtoReflect() protoreflect.Message {
	mi := &file_userclient_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResQuery.ProtoReflect.Descriptor instead.
func (*ResQuery) Descriptor() ([]byte, []int) {
	return file_userclient_proto_rawDescGZIP(), []int{4}
}

func (x *ResQuery) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *ResQuery) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_userclient_proto protoreflect.FileDescriptor

var file_userclient_proto_rawDesc = []byte{
	0x0a, 0x10, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x67, 0x72,
	0x70, 0x63, 0x22, 0x44, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x22, 0x91, 0x01, 0x0a, 0x07, 0x47, 0x65, 0x74,
	0x42, 0x6f, 0x64, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x68, 0x61, 0x72, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x68, 0x61, 0x72, 0x65, 0x43, 0x68, 0x61, 0x6e,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x68, 0x61, 0x72, 0x65, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x68, 0x61, 0x72, 0x65, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x22, 0xd3, 0x01, 0x0a,
	0x07, 0x50, 0x75, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x53, 0x68, 0x61, 0x72, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x53, 0x68, 0x61, 0x72, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x6c,
	0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x6c, 0x64, 0x22, 0x38, 0x0a, 0x0a, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x36, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x32, 0xd6, 0x01, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x03, 0x47, 0x65,
	0x74, 0x12, 0x17, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x18, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3e, 0x0a, 0x03, 0x50, 0x75,
	0x74, 0x12, 0x17, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x50, 0x75, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x1a, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x28, 0x01, 0x12, 0x41, 0x0a, 0x07, 0x4e, 0x65,
	0x77, 0x75, 0x73, 0x65, 0x72, 0x12, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x1a,
	0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x42, 0x02, 0x50,
	0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_userclient_proto_rawDescOnce sync.Once
	file_userclient_proto_rawDescData = file_userclient_proto_rawDesc
)

func file_userclient_proto_rawDescGZIP() []byte {
	file_userclient_proto_rawDescOnce.Do(func() {
		file_userclient_proto_rawDescData = protoimpl.X.CompressGZIP(file_userclient_proto_rawDescData)
	})
	return file_userclient_proto_rawDescData
}

var file_userclient_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_userclient_proto_goTypes = []interface{}{
	(*UserInfo)(nil),   // 0: userclientgrpc.UserInfo
	(*GetBody)(nil),    // 1: userclientgrpc.GetBody
	(*PutBody)(nil),    // 2: userclientgrpc.PutBody
	(*VerifyInfo)(nil), // 3: userclientgrpc.VerifyInfo
	(*ResQuery)(nil),   // 4: userclientgrpc.ResQuery
}
var file_userclient_proto_depIdxs = []int32{
	1, // 0: userclientgrpc.UserClientService.Get:input_type -> userclientgrpc.GetBody
	2, // 1: userclientgrpc.UserClientService.Put:input_type -> userclientgrpc.PutBody
	0, // 2: userclientgrpc.UserClientService.Newuser:input_type -> userclientgrpc.UserInfo
	4, // 3: userclientgrpc.UserClientService.Get:output_type -> userclientgrpc.ResQuery
	3, // 4: userclientgrpc.UserClientService.Put:output_type -> userclientgrpc.VerifyInfo
	3, // 5: userclientgrpc.UserClientService.Newuser:output_type -> userclientgrpc.VerifyInfo
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_userclient_proto_init() }
func file_userclient_proto_init() {
	if File_userclient_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_userclient_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userclient_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userclient_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userclient_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userclient_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_userclient_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userclient_proto_goTypes,
		DependencyIndexes: file_userclient_proto_depIdxs,
		MessageInfos:      file_userclient_proto_msgTypes,
	}.Build()
	File_userclient_proto = out.File
	file_userclient_proto_rawDesc = nil
	file_userclient_proto_goTypes = nil
	file_userclient_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserClientServiceClient is the client API for UserClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClientServiceClient interface {
	Get(ctx context.Context, opts ...grpc.CallOption) (UserClientService_GetClient, error)
	Put(ctx context.Context, opts ...grpc.CallOption) (UserClientService_PutClient, error)
	Newuser(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*VerifyInfo, error)
}

type userClientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClientServiceClient(cc grpc.ClientConnInterface) UserClientServiceClient {
	return &userClientServiceClient{cc}
}

func (c *userClientServiceClient) Get(ctx context.Context, opts ...grpc.CallOption) (UserClientService_GetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UserClientService_serviceDesc.Streams[0], "/userclientgrpc.UserClientService/Get", opts...)
	if err != nil {
		return nil, err
	}
	x := &userClientServiceGetClient{stream}
	return x, nil
}

type UserClientService_GetClient interface {
	Send(*GetBody) error
	Recv() (*ResQuery, error)
	grpc.ClientStream
}

type userClientServiceGetClient struct {
	grpc.ClientStream
}

func (x *userClientServiceGetClient) Send(m *GetBody) error {
	return x.ClientStream.SendMsg(m)
}

func (x *userClientServiceGetClient) Recv() (*ResQuery, error) {
	m := new(ResQuery)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userClientServiceClient) Put(ctx context.Context, opts ...grpc.CallOption) (UserClientService_PutClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UserClientService_serviceDesc.Streams[1], "/userclientgrpc.UserClientService/Put", opts...)
	if err != nil {
		return nil, err
	}
	x := &userClientServicePutClient{stream}
	return x, nil
}

type UserClientService_PutClient interface {
	Send(*PutBody) error
	CloseAndRecv() (*VerifyInfo, error)
	grpc.ClientStream
}

type userClientServicePutClient struct {
	grpc.ClientStream
}

func (x *userClientServicePutClient) Send(m *PutBody) error {
	return x.ClientStream.SendMsg(m)
}

func (x *userClientServicePutClient) CloseAndRecv() (*VerifyInfo, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(VerifyInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userClientServiceClient) Newuser(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*VerifyInfo, error) {
	out := new(VerifyInfo)
	err := c.cc.Invoke(ctx, "/userclientgrpc.UserClientService/Newuser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserClientServiceServer is the server API for UserClientService service.
type UserClientServiceServer interface {
	Get(UserClientService_GetServer) error
	Put(UserClientService_PutServer) error
	Newuser(context.Context, *UserInfo) (*VerifyInfo, error)
}

// UnimplementedUserClientServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserClientServiceServer struct {
}

func (*UnimplementedUserClientServiceServer) Get(UserClientService_GetServer) error {
	return status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedUserClientServiceServer) Put(UserClientService_PutServer) error {
	return status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (*UnimplementedUserClientServiceServer) Newuser(context.Context, *UserInfo) (*VerifyInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Newuser not implemented")
}

func RegisterUserClientServiceServer(s *grpc.Server, srv UserClientServiceServer) {
	s.RegisterService(&_UserClientService_serviceDesc, srv)
}

func _UserClientService_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UserClientServiceServer).Get(&userClientServiceGetServer{stream})
}

type UserClientService_GetServer interface {
	Send(*ResQuery) error
	Recv() (*GetBody, error)
	grpc.ServerStream
}

type userClientServiceGetServer struct {
	grpc.ServerStream
}

func (x *userClientServiceGetServer) Send(m *ResQuery) error {
	return x.ServerStream.SendMsg(m)
}

func (x *userClientServiceGetServer) Recv() (*GetBody, error) {
	m := new(GetBody)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _UserClientService_Put_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UserClientServiceServer).Put(&userClientServicePutServer{stream})
}

type UserClientService_PutServer interface {
	SendAndClose(*VerifyInfo) error
	Recv() (*PutBody, error)
	grpc.ServerStream
}

type userClientServicePutServer struct {
	grpc.ServerStream
}

func (x *userClientServicePutServer) SendAndClose(m *VerifyInfo) error {
	return x.ServerStream.SendMsg(m)
}

func (x *userClientServicePutServer) Recv() (*PutBody, error) {
	m := new(PutBody)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _UserClientService_Newuser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserClientServiceServer).Newuser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userclientgrpc.UserClientService/Newuser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserClientServiceServer).Newuser(ctx, req.(*UserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserClientService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "userclientgrpc.UserClientService",
	HandlerType: (*UserClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Newuser",
			Handler:    _UserClientService_Newuser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Get",
			Handler:       _UserClientService_Get_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Put",
			Handler:       _UserClientService_Put_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "userclient.proto",
}
